name: Deploy to GitHub Pages

on:
  push:
    branches:
      - development

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: 14
      - name: Build source
        run: |
          npm install
          npm run build
      - run: |
          cp demo/* dist/
          echo $GITHUB_SHA >> dist/index.html
      - name: Deploy to GitHub Pages
        uses: maxheld83/ghpages@v0.3.0
        env:
          BUILD_DIR: dist/
          GH_PAT: ${{ secrets.GH_PAT }}
